services:
  ndmslink_database:
    container_name: "database"
    image: "postgres:13.8"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
    volumes:
      - type: bind
        source: ${PSQL_SOURCE_DATA_VOLUME}
        target: /var/lib/postgresql/data
  cqf:
      container_name: "cqf"
      build: ./cqf-ruler
      environment:
        - spring.datasource.url=${CQF_DB_URL}
        - spring.datasource.username=${CQF_DB_USERNAME}
        - spring.datasource.password=${CQF_DB_PASSWORD}
        - spring.datasource.driver-class-name=org.postgresql.Driver
        - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
        - spring.datasource.max-active=15
        - spring.jpa.properties.hibernate.search.enabled=false
      ports:
        - "9093:8080"
      healthcheck:
        test: ["CMD", "nc", "-vz", "-w1", "localhost", "8080"]
        interval: 30s
        timeout: 10s
        retries: 5
  datastore:
    container_name: "datastore"
    build: ./datastore
    ports:
      - "9092:8080"
    environment:
      - SPRING_CONFIG_LOCATION=file:/datastore/datastore-config.yml
      - datastore.datasource.url=${DATASTORE_DB_URL}
    volumes:
       - type: bind
         source: ${DATASTORE_CONFIG_FILE}
         target: /datastore/datastore-config.yml
    healthcheck:
       test: ["CMD", "nc", "-vz", "-w1", "localhost", "8080"]
       interval: 30s
       timeout: 10s
       retries: 5
